# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install jinja2==3.0
        pip install werkzeug==1.0.1
        pip install itsdangerous==1.1.0
        pip install markupsafe==1.1.1
        
    - name: Deploy no EC2 - AWS
      run: |
        echo "Conectando no EC2"
        echo "${{secrets.AWS_PEM}}" > private_key && chmod 600 private_key 
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-3-82-95-14.compute-1.amazonaws.com "
            cd aws_pratica/;git pull;./iniciarApp.sh"
